name: Deploy Cloudflare Worker  

on:  
  push:  
    branches:  
      - main  # Adjust the branch name as needed  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Set up Node.js  
        uses: actions/setup-node@v3  
        with:  
          node-version: '16'  # Specify the Node.js version  

      - name: Install wrangler  
        run: npm install -g wrangler

      - name: Configure wrangler  
        run: wrangler login  
        env:  
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}  

      - name: Publish to Cloudflare Workers  
        run: wrangler publish  
        env:  
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}  
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
